# Generated by Django 4.2 on 2023-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Product Price'),
        ),
    ]
