# Generated by Django 4.2 on 2023-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart_price'),
        ('users', '0002_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_prod',
            field=models.ManyToManyField(to='main.products'),
        ),
    ]
